apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-app
  ports:
  - name: dotnet-app
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
