apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: nginx
        image: aksacr789.azurecr.io/dotnet-app
        ports:
        - containerPort: 80
