apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dotnet-app
  ports:
  - name: dotnet-app
    protocol: TCP
    port: 80
    targetPort: 80
